DROP DATABASE IF EXISTS employeeDB;
CREATE DATABASE employeeDB;

USE employeeDB;;


CREATE TABLE department(
  id INT PRIMARY KEY NOT NULL,
name VARCHAR(30) NOT NULL, 
);

CREATE TABLE role(
  id INT PRIMARY KEY NOT NULL,
name VARCHAR(30) NOT NULL, 
salary DECIMAL NOT NULL, 
department_id INT NOT NULL,
);


CREATE TABLE employee(
  id INT PRIMARY KEY NOT NULL,
first_name VARCHAR(30) NOT NULL, 
last_name VARCHAR(30) NOT NULL, 
salary DECIMAL NOT NULL, 
role_id INT NOT NULL,
);
